# Generated by Django 4.2.1 on 2023-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocation',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocationtype',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commercialstatus',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
