# Generated by Django 4.2.1 on 2023-06-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0002_remove_allocation_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(choices=[('india', 'India'), ('uk', 'UK'), ('other', 'OTHER')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReccurringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='end_repeat',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='repeat_occurrence',
        ),
        migrations.AddField(
            model_name='allocation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seperation_count', models.IntegerField(default=0, null=True)),
                ('max_num_of_accurrences', models.IntegerField(default=0, null=True)),
                ('day_of_week', models.IntegerField(default=0, null=True)),
                ('week_of_month', models.IntegerField(default=0, null=True)),
                ('day_of_month', models.IntegerField(default=0, null=True)),
                ('month_of_year', models.IntegerField(default=0, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_detail_allocation', to='resource_management_app.allocation')),
                ('reccurring_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_detail_reccurring_type', to='resource_management_app.reccurringtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
