# Generated by Django 4.2.1 on 2023-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0003_holiday_reccurringtype_remove_allocation_end_repeat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='is_recurring',
            new_name='is_reccurring',
        ),
        migrations.AddField(
            model_name='allocation',
            name='no_of_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
