# Generated by Django 4.2.1 on 2023-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0004_rename_is_recurring_allocation_is_reccurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationdetail',
            name='reccurring_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
