# Generated by Django 4.2.1 on 2023-06-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0005_alter_allocationdetail_reccurring_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='is_reccurring',
        ),
    ]
