# Generated by Django 4.2.1 on 2023-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management_app', '0006_remove_allocation_is_reccurring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holiday',
            new_name='BankHoliday',
        ),
    ]
